WIDTH                                    1950                          
FILE_LENGTH                              2219                          
XMIN                                     0                             
XMAX                                     1949                          
YMIN                                     0                             
YMAX                                     2218                          
RLOOKS                                   1                             
ALOOKS                                   1                             
X_FIRST                                  89.539999784                  
X_STEP                                   0.000833333                   
X_UNIT                                   degrees                       
Y_FIRST                                  30.848333394                  
Y_STEP                                   -0.000833333                  
Y_UNIT                                   degrees                       
TIME_SPAN_YEAR                           -0.0970225872689938           
COR_THRESHOLD                            0.3                           
ORBIT_NUMBER                             34799-34298                   
VELOCITY                                 7553.8223332436               
HEIGHT                                   0.7875814699E+06              
EARTH_RADIUS                             6352349.68331266              
WAVELENGTH                               0.0562356424                  
DATE                                     081026                        
DATE12                                   081026-080921                 
HEADING_DEG                              -166.7393                     
RGE_REF1                                 824.1402                      
LOOK_REF1                                16.1317                       
LAT_REF1                                 30.6350                       
LON_REF1                                 91.1635                       
RGE_REF2                                 868.4668                      
LOOK_REF2                                23.4194                       
LAT_REF2                                 30.8484                       
LON_REF2                                 89.9743                       
RGE_REF3                                 824.1402                      
LOOK_REF3                                16.1913                       
LAT_REF3                                 28.7979                       
LON_REF3                                 90.7046                       
RGE_REF4                                 868.4668                      
LOOK_REF4                                23.4589                       
LAT_REF4                                 29.0107                       
LON_REF4                                 89.5397                       
